email: <Email>
library:
  source-dirs:
  - src
  other-modules: []
category: Web
ghc-options: -Wall -fno-warn-partial-type-signatures -fno-warn-missing-methods -fno-warn-unused-do-bind
  -rtsopts -threaded
dependencies:
- base
- pure
- pure-elm
- pure-conjurer
- pure-json
- pure-render
- pure-router
- pure-sorcerer
- pure-transform
- pure-txt
- pure-websocket
- hashable
default-extensions:
- AutoDeriveTypeable
- BangPatterns
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyCase
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImplicitParams
- InstanceSigs
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- PartialTypeSignatures
- PatternGuards
- PatternSynonyms
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeApplications
- TypeFamilies
- TypeFamilyDependencies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns
- TemplateHaskell
- BlockArguments
- PostfixOperators
- DerivingVia
- DerivingStrategies
name: shared
version: 0.1.0.0
synopsis: shared types and apis
author: <Author>
ghcjs-options: -threaded -dedupe -DGHCJS_BROWSER -DGHCJS_GC_INTERVAL=3000000
license: BSD3
