name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-10.15]  

    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: purehs
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'

    - name: build
      run: |
        nix-build -o result -A ghc.backend
        nix-build -o result -A ghc.server
        nix-build -o result -A ghcjs.frontend

